spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  frontend-url: http://localhost:4200
  security:
    public-endpoints:
      - /auth/**
      - /oauth2/**
      - /actuator/**