spring:
  application:
    name: spring-ai-chatbot
  ai:
    openai:
      api-key: dummy-api-key
      base-url: dummy-base-url
      chat:
        options:
          model: dummy-model

#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        options:
#          model: qwen2.5:7b
