-- =========================
-- USER TABLE
-- =========================
CREATE TABLE app_user
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name           VARCHAR(255),
    email               VARCHAR(255) NOT NULL,
    password            VARCHAR(255),

    provider_type       VARCHAR(50)  NOT NULL,
    provider_id         VARCHAR(255),

    verified            BOOLEAN   DEFAULT FALSE,
    verified_date       TIMESTAMP,

    created_date        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    password_reset_date TIMESTAMP
);

-- Unique constraint on email
ALTER TABLE app_user
    ADD CONSTRAINT uk_user_email UNIQUE (email);

-- Check Constraint for provider_type
ALTER TABLE app_user
    ADD CONSTRAINT chk_app_user_provider_type
        CHECK (provider_type IN ('LOCAL', 'GOOGLE', 'GITHUB'));

-- Index for OAuth/provider lookup
CREATE INDEX idx_user_provider_id_provider_type
    ON app_user (provider_id, provider_type);


-- =========================
-- USER ROLES (ElementCollection)
-- =========================
CREATE TABLE app_user_roles
(
    user_id BIGINT NOT NULL,
    role    VARCHAR(50) NOT NULL,

    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE,

    CONSTRAINT uk_user_roles
        UNIQUE (user_id, role),

    CONSTRAINT chk_user_roles
        CHECK (role IN ('ROLE_USER', 'ROLE_ADMIN'))
);


-- =========================
-- USER EXTRA PERMISSIONS (ElementCollection)
-- =========================
CREATE TABLE app_user_extra_permissions
(
    user_id    BIGINT       NOT NULL,
    permission VARCHAR(100) NOT NULL,

    CONSTRAINT fk_user_extra_permissions_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE,

    CONSTRAINT uk_user_extra_permissions UNIQUE (user_id, permission)
);


-- =========================
-- USER REVOKED PERMISSIONS (ElementCollection)
-- =========================
CREATE TABLE app_user_revoked_permissions
(
    user_id    BIGINT       NOT NULL,
    permission VARCHAR(100) NOT NULL,

    CONSTRAINT fk_user_revoked_permissions_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE CASCADE,

    CONSTRAINT uk_user_revoked_permissions UNIQUE (user_id, permission)
);


-- =========================
-- TOKEN USAGE AUDIT TABLE
-- =========================
CREATE TABLE token_usage_audit
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id           BIGINT,
    model             VARCHAR(100),
    provider          VARCHAR(100),

    prompt_tokens     INT NOT NULL,
    completion_tokens INT NOT NULL,
    total_tokens      INT NOT NULL,

    cost_in_usd       DOUBLE PRECISION,
    latency_sec       DOUBLE PRECISION,

    input_summary     TEXT,
    output_summary    TEXT,

    created_date      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tua_user
        FOREIGN KEY (user_id)
            REFERENCES app_user (id)
            ON DELETE SET NULL
);

-- Index for user + time-based queries
CREATE INDEX idx_tua_user_created_id
    ON token_usage_audit (user_id, created_date, id);

CREATE INDEX idx_tua_created_date_id
    ON token_usage_audit (created_date, id);