-- =========================================================
-- ACCESS REQUEST
-- =========================================================
CREATE TABLE access_request
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id      BIGINT      NOT NULL,
    reviewer_id       BIGINT,

    status            VARCHAR(30) NOT NULL DEFAULT 'PENDING',

    requester_comment TEXT,
    reviewer_comment  TEXT,

    requested_date    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_date     TIMESTAMP,
    created_date      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_date      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Optimistic locking
--     version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_access_request_requester
        FOREIGN KEY (requester_id)
            REFERENCES app_user (id),

    CONSTRAINT fk_access_request_reviewer
        FOREIGN KEY (reviewer_id)
            REFERENCES app_user (id),

    CONSTRAINT chk_access_request_status
        CHECK (
            status IN (
                       'PENDING',
                       'APPROVED',
                       'REJECTED',
                       'CANCELLED'
                )
            )
);

CREATE INDEX idx_access_request_requester
    ON access_request (requester_id);

CREATE INDEX idx_access_request_reviewer
    ON access_request (reviewer_id);

CREATE INDEX idx_access_request_status
    ON access_request (status);

CREATE INDEX idx_access_request_requested_date
    ON access_request (requested_date);



-- =========================================================
-- REQUESTED ROLES
-- =========================================================
CREATE TABLE access_request_roles
(
    request_id BIGINT      NOT NULL,
    role       VARCHAR(50) NOT NULL,

    CONSTRAINT fk_access_request_roles_request
        FOREIGN KEY (request_id)
            REFERENCES access_request (id)
            ON DELETE CASCADE,

    CONSTRAINT uk_access_request_role
        UNIQUE (request_id, role),

    CONSTRAINT chk_access_request_role
        CHECK (role IN ('ROLE_ANALYST', 'ROLE_MANAGER', 'ROLE_ADMIN'))
);

CREATE INDEX idx_access_request_roles_request
    ON access_request_roles (request_id);



-- =========================================================
-- REQUESTED PERMISSIONS
-- =========================================================
CREATE TABLE access_request_permissions
(
    request_id BIGINT       NOT NULL,
    permission VARCHAR(100) NOT NULL,

    CONSTRAINT fk_access_request_permissions_request
        FOREIGN KEY (request_id)
            REFERENCES access_request (id)
            ON DELETE CASCADE,

    CONSTRAINT uk_access_request_permission
        UNIQUE (request_id, permission)
);

CREATE INDEX idx_access_request_permissions_request
    ON access_request_permissions (request_id);